name: DAST with OWASP ZAP

on:
  push:

jobs:
  build_application:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Set build date as image tag
        id: set_tag
        run: |
          echo "image_tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          echo "::set-output name=image_tag::$(date +'%Y%m%d%H%M%S')"

  build_docker_image:
    needs: build_application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build --tag ${{ env.IMAGE_NAME }}:${{ needs.build_application.outputs.image_tag }} .
          docker push ${{ env.IMAGE_NAME }}:${{ needs.build_application.outputs.image_tag }}

  perform_dast_scan:
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_NAME }}:${{ needs.build_docker_image.outputs.image_tag }}

      - name: Run Docker container
        run: docker run -d -p 8888:8888 --name myapp ${{ env.IMAGE_NAME }}:${{ needs.build_docker_image.outputs.image_tag }}

      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'http://localhost:8888'
          docker_name: 'owasp/zap2docker-stable'
          cmd_options: '-t ${TARGET_URL} -r zap_report.html'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
