name: Deploy to GKE

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/ngtianxun08/myapp/myimage:latest
#   PROJECT_ID: ${{ secrets.PROJECT_ID }}
#   GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
#   GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - run: mvn clean install --batch-mode --errors --fail-at-end
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gcpdeployment-0.0.1-SNAPSHOT.jar
          path: target/
  build-docker-image:
    name: build-docker
    needs: setup-build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Retrieve saved jar
        uses: actions/download-artifact@v2
        with:
          name: gcpdeployment-0.0.1-SNAPSHOT.jar
          path: target/

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          USERNAME: ${{ secrets.GHCR_USERNAME }}
          PASSWORD: ${{ secrets.GHCR_PASSWORD }}
        run: |
          echo $GHCR_PASSWORD | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
          docker build --tag $IMAGE_NAME .
          docker push $IMAGE_NAME          

#   deploy-to-gke:
#     needs: build-docker-image
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: kubectl - Google Cloud GKE cluster.
#         uses: ameydev/gke-kubectl-action@master
#         env:
#           PROJECT_ID: ${{ secrets.PROJECT_ID }}
#           APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
#           CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
#           ZONE_NAME: ${{ secrets.GKE_ZONE }}
#         with:
#           args: apply -f k8s/