name: "sast-scan"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: OWASP Dependency Check and Run Scan with ODC
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.2.0/dependency-check-7.2.0-release.zip
          unzip dependency-check-7.2.0-release.zip
          ./dependency-check/bin/dependency-check.sh --project "FlightBackend" --scan ./src/main/java -f XML -o ./sast-report

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sast report
          path: |
            ./sast-report
